server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthflow
    username: postgres
    password: TmX85col1978
  jpa:
    hibernate:
      ddl-auto: validate # <-- CAMBIADO a 'validate'
    properties:
      hibernate:
        jdbc:
          time_zone: America/Bogota
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

healthflow:
  timezone: America/Bogota
  publicBaseUrl: http://localhost:8080
  appointment:
    slotMinutes: 30
    minLeadMinutes: 120
  seed:
    enabled: true
  upload-dir: uploads # ← nueva
  document:
      expiration-days: 7
