-- Diagnósticos comunes para medicina general y especialidades
INSERT INTO diagnosticos_cie10 (codigo, descripcion) VALUES
('A09', 'Diarrea y gastroenteritis de presunto origen infeccioso'),
('E10', 'Diabetes mellitus insulinodependiente'),
('E11', 'Diabetes mellitus no insulinodependiente'),
('I10', 'Hipertensión esencial (primaria)'),
('J00', 'Rinofaringitis aguda (resfriado común)'),
('J01', 'Sinusitis aguda'),
('J02', 'Faringitis aguda'),
('J03', 'Amigdalitis aguda'),
('J06', 'Infecciones agudas de las vías respiratorias superiores'),
('J15', 'Neumonía bacteriana no clasificada en otra parte'),
('J20', 'Bronquitis aguda'),
('J30', 'Rinitis alérgica'),
('J45', 'Asma'),
('M54', 'Dorsalgia'),
('M79', 'Fibromialgia'),
('M79.1', 'Mialgia'),
('M62.8', 'Otros trastornos especificados del músculo'),
('N39', 'Trastornos del tracto urinario'),
('R05', 'Tos'),
('R10', 'Dolor abdominal y pélvico'),
('R11', 'Náusea y vómito'),
('R51', 'Cefalea'),
('Z23', 'Vacunación contra enfermedades infecciosas'),
('Z29', 'Otras profilaxis inmunológicas'),
('Z30', 'Anticoncepción'),
('Z31', 'Procedimientos de procreación'),
('Z32', 'Examen o prueba de embarazo'),
('Z34', 'Supervisión de embarazo normal'),
('Z76', 'Persona en contacto con servicios de salud por otras circunstancias')
ON CONFLICT (codigo) DO NOTHING;