-- =====================================================
-- Migración V9: Insertar datos maestros para catálogos RIPS
-- =====================================================

-- Insertar finalidades de consulta (solo si no existen)
INSERT INTO catalogo_finalidad_consulta (codigo, descripcion) VALUES
                                                                  ('01', 'Detección temprana - Alteraciones del desarrollo del joven (de 10 a 29 años)'),
                                                                  ('02', 'Detección temprana - Alteraciones del embarazo'),
                                                                  ('03', 'Detección temprana - Alteraciones del adulto (de 45 a 59 años)'),
                                                                  ('04', 'Detección temprana - Cáncer de cuello uterino'),
                                                                  ('05', 'Detección temprana - Cáncer de mama'),
                                                                  ('06', 'Detección temprana - Alteraciones de la agudeza visual'),
                                                                  ('07', 'Protección específica - Vacunación'),
                                                                  ('08', 'Protección específica - Atención preventiva en salud bucal'),
                                                                  ('09', 'Protección específica - Atención preventiva en salud mental'),
                                                                  ('10', 'Protección específica - Planificación familiar'),
                                                                  ('11', 'Protección específica - Atención del parto'),
                                                                  ('12', 'Protección específica - Atención del recién nacido'),
                                                                  ('13', 'Protección específica - Atención en planificación familiar hombres'),
                                                                  ('14', 'Detección temprana - Enfermedad renal crónica'),
                                                                  ('15', 'Detección temprana - Hipertensión arterial'),
                                                                  ('16', 'Detección temprana - Diabetes mellitus'),
                                                                  ('17', 'Detección temprana - Alteraciones metabólicas'),
                                                                  ('18', 'Protección específica - Crecimiento y desarrollo (menores de 10 años)'),
                                                                  ('19', 'Demanda inducida - Vacunación'),
                                                                  ('20', 'Demanda inducida - Control de enfermedades crónicas'),
                                                                  ('21', 'Demanda inducida - Consulta por morbilidad'),
                                                                  ('22', 'Consulta de primera vez'),
                                                                  ('23', 'Consulta de control o seguimiento'),
                                                                  ('24', 'Consulta de urgencias'),
                                                                  ('25', 'Consulta domiciliaria'),
                                                                  ('26', 'Consulta a instituciones cerradas (cárceles, ancianatos, etc.)'),
                                                                  ('27', 'Teleconsulta'),
                                                                  ('28', 'Junta médica'),
                                                                  ('29', 'Interconsulta'),
                                                                  ('30', 'Consulta de promoción y mantenimiento de la salud'),
                                                                  ('31', 'Consulta para la prescripción de tecnologías en salud'),
                                                                  ('32', 'Consulta para la certificación de incapacidad'),
                                                                  ('33', 'Consulta por primera vez por medicina especializada'),
                                                                  ('34', 'Consulta de control por medicina especializada'),
                                                                  ('99', 'Otra finalidad')
    ON CONFLICT (codigo) DO NOTHING;

-- Insertar causas externas
INSERT INTO catalogo_causa_externa (codigo, descripcion) VALUES
                                                             ('01', 'Accidente de trabajo'),
                                                             ('02', 'Accidente de tránsito'),
                                                             ('03', 'Accidente doméstico'),
                                                             ('04', 'Accidente de otro tipo'),
                                                             ('05', 'Agresión (atentado, maltrato, violencia)'),
                                                             ('06', 'Lesión autoinfligida (intento de suicidio)'),
                                                             ('07', 'Sospecha de maltrato físico'),
                                                             ('08', 'Sospecha de abuso sexual'),
                                                             ('09', 'Sospecha de violencia sexual'),
                                                             ('10', 'Enfermedad general'),
                                                             ('11', 'Enfermedad profesional'),
                                                             ('12', 'Condiciones maternas'),
                                                             ('13', 'Condiciones perinatales'),
                                                             ('14', 'Enfermedad huérfana (rara)'),
                                                             ('15', 'Accidente biológico'),
                                                             ('16', 'Otra causa externa'),
                                                             ('17', 'Intoxicación por plaguicidas'),
                                                             ('18', 'Intoxicación por fármacos'),
                                                             ('19', 'Intoxicación por otros químicos'),
                                                             ('20', 'Efecto adverso por droga lícita'),
                                                             ('21', 'Efecto adverso por droga ilícita'),
                                                             ('22', 'Efecto adverso por medicamentos'),
                                                             ('23', 'Reacción adversa a vacuna'),
                                                             ('24', 'Evento adverso durante procedimiento quirúrgico'),
                                                             ('25', 'Evento adverso durante procedimiento médico'),
                                                             ('26', 'Complicación de implante o injerto'),
                                                             ('27', 'Complicación de dispositivo médico'),
                                                             ('28', 'Reacción adversa a transfusión'),
                                                             ('29', 'Evento adverso durante atención en salud'),
                                                             ('30', 'Lesión por reacción medicamentosa'),
                                                             ('99', 'Otra')
    ON CONFLICT (codigo) DO NOTHING;